### ISSUE TITLE
hw3 - ЗАЧЕТ

### ISSUE THREAD

**Issue by KipariS** [Valerika/Valerika.github.io#2]
Будет круто если ты поправишь следующее:
- лого (зачастую) делают ссылкой на главную (в данном случае href="#")
- в верхнем меню должен быть гредиент 
- боковое меню должно быть в рамке
- под картинкой должен быть отступ
- в нижней меню при наведении подчеркнутый текст
И
Явно не тот шрифт подключен.

Будет чтото не понятно не стесняйс пиши в скайп.

**Comment by Valerika** [comment]
Откорректировала
